src/blueprints/assistant.py
from flask import Blueprint, render_template,request,session,redirect,url_for
import db, datetime

bp = Blueprint('assistant', __name__, url_prefix='/')
time = datetime.date.today()

"""
李树昊写的函数↓ 优化：李佩伦
"""


@bp.route("/assistant",methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        title=''
        category=''
        poeple=''
        date=''
        user_name = session['username']
        context = {'user_name': user_name,'title':title,'category':category,'poeple':poeple,'date':date}
        return render_template("check.html",**context)
    else:
        data = db.Database()
        title = request.form.get('topic')
        category = request.form.get('category')
        content = request.form.get('content')
        people = request.form.get('people')
        date = request.form.get('date')
        doctors = data.get_doctors()
        articles = data.get_articles()
        doctor_id = None
        for doctor in doctors:
            if doctor[1] == people:
                doctor_id = doctor[0]
        if title != None and category != None and content != None and people != None and date != None:
            article_id=None
            for article in articles:
                if article[3] == content:
                    article_id=article[0]
            data.remove_article_by_id(article_id)
            data.insert_article(name=title, author=doctor_id, content=content, tags=category, date=date,status="published")
            print(title)
            print(category)
            print(date)
            print(content)
            print(doctor_id)
            return redirect("/assistant")
        else:
            return redirect("/assistant")


"""
李树昊写的函数↓ 优化：李佩伦
"""


@bp.route("/create_account2", methods=['GET', 'POST'])
def create_account2():
    if request.method == 'GET':
        user_name = session['username']
        context = {'user_name':user_name,'value':'可输入数字\字母\二者混合'}
        return render_template("register.html",**context)
    else:
        user_name = session['username']
        identity = request.form.get('identity')
        username = request.form.get('username')
        password = request.form.get('password')
        confirmPwd = request.form.get("confirmPwd")
        email = request.form.get("email")
        print(identity)
        print(username)
        print(password)
        print(confirmPwd)
        print(email)
        if username == None or password == None or confirmPwd == None or email == None:
            context = {'user_name':user_name,'value': '可输入数字\字母\二者混合'}
            return render_template("register-doctor.html", **context)
        if password != confirmPwd:
            context = {'user_name':user_name,'value': '所输入密码不一致,请重输'}
            return render_template("register.html",**context)
        data = db.Database()
        if identity == "医师":
            data.insert_doctor(username, password)
        elif identity == "医师助理":
            data.insert_assistant(username, password)
        elif identity == "病人":
            data.insert_patient(username,password,email,diagnosis='',tags='')
        return redirect(url_for("index.login"))


"""
李树昊写的函数↓
"""


@bp.route("/check_feedback")
def check_feedback():
    user_name = session['username']
    context = {'user_name': user_name}
    return render_template("feedback.html",**context)


"""
李佩伦写的函数↓
"""


@bp.route("/saved_article")
def saved_article():
    data = db.Database()
    articles = data.get_articles()
    target_article3 = []
    article_time3 = []
    article_sorted_by_time3 = []
    for article in articles:
        if article[6] == "saved":
            target_article3.append(article)
            article_time3.append(article[5])
    article_time_set = set(article_time3)
    article_time_true = list(article_time_set)
    article_time_true.sort(reverse=True)
    for the_time in article_time_true:
        for article in target_article3:
            if article[5] == the_time:
                article_sorted_by_time3.append(article)
    context = {'target_article': target_article3,"article_sorted_by_time3":article_sorted_by_time3}
    return render_template('draft_assistant.html', **context)


"""
李树昊写的函数↓
"""


@bp.route("/assistant/<the_id>", methods=['GET', 'POST'])
def test(the_id):
    if request.method == 'GET':
        data=db.Database()
        a_list = data.get_article_by_id(the_id)
        doctors = data.get_doctors()
        people = None
        for doctor in doctors:
            if doctor[0] == a_list[2]:
                people = doctor[1]
        user_name = session['username']
        context = {'user_name': user_name, 'title': a_list[1], 'category': a_list[4], 'content':a_list[3],'poeple': people, 'date': a_list[5],'the_id':the_id}
        return render_template("check_article_assistant.html", **context)
    else:
        data = db.Database()
        title = request.form.get('topic')
        category = request.form.get('category')
        content = request.form.get('content')
        people = request.form.get('people')
        date = request.form.get('date')
        doctors = data.get_doctors()
        articles = data.get_articles()
        doctor_id = None
        for doctor in doctors:
            if doctor[1] == people:
                doctor_id = doctor[0]
        if title != None and category != None and content != None and people != None and date != None:
            article_id = None
            for article in articles:
                if article[3] == content:
                    article_id = article[0]
            data.remove_article_by_id(article_id)
            data.insert_article(name=title, author=doctor_id, content=content, tags=category, date=date,
                                status='published')
            print(title)
            print(category)
            print(date)
            print(content)
            print(doctor_id)
            return redirect("/assistant")
        else:
            return redirect("/assistant")


"""
李佩伦写的函数↓
"""


@bp.route('/reject_article/<id>',methods=['GET'])
def rejected_article(id):
    data = db.Database()
    article=data.get_article_by_id(id)
    article_name=article[1]
    article_author=article[2]
    article_content=article[3]
    article_tag=article[4]
    article_date=article[5]
    data.remove_article_by_id(id)
    data.insert_article(name=article_name,author=article_author,content=article_content,tags=article_tag,date=article_date,status='rejected')
    return redirect(url_for('assistant.login'))


"""
李树昊写的函数↓
"""


@bp.route('/change_article/<id>',methods=['GET','post'])
def change_article(id):
    data = db.Database()
    title = request.form.get('topic')
    category = request.form.get('category')
    content = request.form.get('content')
    a_list = data.get_article_by_id(id)
    doctors = data.get_doctors()
    doctor_id = None
    for doctor in doctors:
        if doctor[0] == a_list[2]:
            doctor_id = doctor[0]
    print(title)
    print(category)
    print(time)
    print(content)
    print(doctor_id)
    data.insert_article(name=title, author=doctor_id, content=content, tags=category, date=time)
    data.remove_article_by_id(id)
    return redirect(url_for('assistant.login'))

src/blueprints/feedback.py
from flask import Blueprint, render_template, request, redirect, session, url_for
import db

bp = Blueprint('feedback', __name__)

@bp.route('/feedback/', methods=['GET'], defaults={'id': None})
@bp.route('/feedback/read/<int:id>', methods=['GET'])
def feedback(id):
    if request.method == 'GET':
        if id is None:
            # 查看所有反馈
            username = session.get('username')
            d = db.Database()
            feedbacks = d.get_feedbacks()
            return render_template('feedback.html', feedbacks=feedbacks, id=None, username=username)
        else:
            # 查看指定反馈
            d = db.Database()
            feedback = d.get_feedback_by_id(id)
            return render_template('feedback.html', feedback=feedback, id=id)

@bp.route('/feedback/add/', methods=['GET', 'POST'])
def add_feedback():
    if request.method == 'GET':
        return render_template('feedback.html', add=True)
    elif request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        print("插入反馈：", type, title, content)
        d = db.Database()
        d.insert_feedback(title, content)
        return redirect("/patient")

src/blueprints/patient.py
from flask import Blueprint,render_template,session,request
import db


bp = Blueprint('patient', __name__, url_prefix='/')


@bp.route('/patient',methods=['GET', 'POST'])
def patient():
    user_name = session['username']
    data = db.Database()
    pushed_article = []
    articles = data.get_articles()
    patient = data.get_patient_by_name(name=user_name)
    for article in articles:
        if article[6] == 'published':
            pushed_article.append(article)
    print(articles)
    print(patient)
    ills = patient[0][5].split(";")
    context = {'user_name':user_name,'ill': ills, 'articles': pushed_article}
    return render_template("patientmain.html", **context)


@bp.route('/detailed_information')
def state():
    user_name = session['username']
    context = {'user_name': user_name}
    return render_template("see_article.html", **context)

src/templates/check_article_assistant.html
<!DOCTYPE html>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/Other/html.html to edit this template
-->
<html>
    <head>
        <title>助理主页</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='check.css') }}">
    </head>
    <body>
        <div id="container">
            <div id="title"> 您好{{user_name}}助理</div>
            <div id="navlink">
                <ul>
                    <li style="background-color:rgb(18, 211, 20);"><a href="/assistant">个人主页</a></li>
                    <li><a href="/create_account2">创建账号</a></li>
                    <li><a href="/check_feedback">查看反馈</a></li>
                </ul>
            </div>
            <div id="toip">
                锦华中医诊所
            </div>
            <div id="left">
                <form id="article" action="/assistant/{{the_id}}" method="POST" name="recheck">
                    <div id="article_title" class="kind">
                        &emsp;&emsp;<span>主题 : <input type="text" id="topic" name="topic" value="{{title}}" placeholder="请选择文章" ></span>&emsp;&emsp;&emsp;&emsp;&emsp;
                        <span>类别 : <input type="text" id="category" name="category" value="{{category}}" placeholder="请选择文章" ></span>
                        <br>
                        <span style="float:left">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;发布人 : <input type="text" id="people" name="people" value="{{poeple}}" placeholder="请选择文章" ></span>
                        <span style="float:left">&emsp;&emsp;&emsp; 日期 : <input type="text" id="date" name="date" value="{{date}}" placeholder="请选择文章" ></span>
                    </div>

                <div id="article_content"><textarea name="content" placeholder="请输入标题" style="width: 99.5%;height: 99%;resize: none;border: blue">{{content}}</textarea></div>
                <div id="patient_tag" class="kind" style="padding-top:17px"><span>推送对象类别：<input type="text" id="disease" name="disease" value="针对{{category}}类患者" placeholder="请选择文章" ></span></div>
                <input type="submit" id="topics" value="推送" style="width: 32.5%;background-color:rgb(25, 207, 89);height: 50px;color: white;font-size: 30px;float: left;border: none;">
                    <a href=" /reject_article/{{the_id}} " onclick= "reject();return false" style="width: 32.5%;background-color:rgb(237, 83, 83);height: 50px;color: white;font-size: 30px;float: left;border: none;">退回</a>
                <input type="submit" id="change" value="修改" onclick= "rechange();return false" style="width: 30.5%;background-color:rgb(255, 204, 85);height: 50px;color: white;font-size: 30px;float: left;border: none;">
                </form>
            </div>
            <div id="right">
                <h1 style="color:rgb(18, 211, 20)">待推送的文章</h1>
                    <iframe src="/saved_article" style="border:1px inset lightseagreen;width:99%;height:490px" ></iframe>
            </div>
            <div id="contactinformation" style="color:white">
                <span style="color:rgb(18, 211, 20)">Traditional Chinese medicine</span>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<span style="color:rgb(148, 155, 149)"> 联系邮箱：plli2021@lzu.edu.cn 联系电话；13831122775</span>
            </div>
        </div>
    <script>
        function reject(){
        if (confirm ("确定退回该文章?")){
        a.setAttribute("onclick",'');
        return true;
        }
        return false;
        }
        function rechange(){
        document.recheck.action="/change_article/{{the_id}}";
        if (confirm ("确定修改该文章?")){
        a.setAttribute("onclick",'');
        return true;
        }
        return false;
        }
    </script>
    </body>
</html>

src/templates/draft.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> draft </title>
</head>
<body>
<ol style="font-size:30px;font-family: Noto Sans SC;">
            {% for article in target_article %}
             <li>
                 <div style="width:100%;float:left;font-size:30px;font-family: Noto Sans SC;"> <a href="{{url_for('doctor.test', the_id = target_article[loop.index0][0])}}" target="_parent">{{ article[1] }}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{article[5]}}</a> </div>
             <br><br>
             </li>
            {% endfor %}
        </ol>
</body>
</html>

src/templates/draft_assistant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> draft </title>
</head>
<body>
<ol style="font-size:30px;font-family: Noto Sans SC;width:98%;">
            {% for article in article_sorted_by_time3 %}
             <li>
                 <div style="width:100%;float:left;font-size:30px;font-family: Noto Sans SC;"> <a href="{{url_for('assistant.test', the_id = article_sorted_by_time3[loop.index0][0])}}" target="_parent">{{ article[1] }}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{article[5]}}</a> </div>
             <br><br>
             </li>
            {% endfor %}

        </ol>
</body>
</html>

src/templates/edit_patient_information_after_search.html
<!DOCTYPE html>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/Other/html.html to edit this template
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <style type="text/css">
body {
width:100%;height:100%;}
#container{width:100%;margin:auto;text-align:center;}
#title{color: rgb(239, 125, 32);font-family: Noto Sans SC;width:25%;height:55px;float:left;border: 3px ;margin:0px 0px 5px 0px;font-size:40px;padding-top:20px;font-weight:900}
#navlink{width:50%;height:35px;float:right;margin:25px 0px 20px 0px}
#toip{width:98.5%;height:65px;background-color:rgb(18, 211, 20);font-size:51px;color:white;float:left;margin:0px 0px 0px 2px}
#left{width:62%;height:580px;float:left;border:1px solid #0490f1;margin:3px 1px}
#article_title{width: 95%;height: 65px;float:left; border:1px solid #0490f1;margin:3px 1px}
#article_content{width: 95%;height: 380px;float:left; border:1px solid #0490f1;margin:3px 1px}
#patient_tag{width: 95%;height: 60px;float:left; border:1px solid #0490f1;margin:3px 1px}
#push{width: 30%;height: 55px;float:left; border:1px solid #0490f1;margin:3px 1px;color: white;background-color: lightgreen}
#delete{width: 30%;height: 55px;float:left; border:1px solid #0490f1;margin:3px 1px;color: white;background-color: red}
#edit{width: 30%;height: 55px;float:left; border:1px solid #0490f1;margin:3px 1px;background-color: yellow}
#right{width:37%;height:580px;float:left;border:1px solid #2f4f4f;margin:3px 1px;color: white;}
#transformation{width: 95%;height: 520px;float:left; border:1px solid #0490f1;margin:3px 1px}
#transformation_title{width: 98.5%;height: 40px;float:left; border:1px solid #0490f1;margin:3px 1px}
#contactinformation{width:98.5%;height:35px;float:left;margin:0px 3px 0px 1px;font-size:20px;padding-top:8px;border:2px solid rgb(18, 211, 20)}
div span input{
width:15%;
height: 20px;
background-color:rgb(230, 250, 230);
border: none;
}
div span{
    color: rgb(22, 196, 46);
    font-size: 20px;
}
a{text-decoration:none;
}
a:link{color:black}
ul{
    list-style-type:none;;
    margin:0;
    padding:0;
    overflow:hidden;
}
li{
    float:left;
    width:20%;
    height:40px;
    margin-left:50px;
    border-radius:20px
}
li a {
    display:inline-block;
    text-align:center;
    padding-top:5px;
    font-size:20px
}
li:hover{
    background-color:lawngreen
}

li:active{
    background-color:lightgreen;
}


</style>
    </head>
    <body>
        <div id="container">
            <div id="title"> 您好 {{user_name}} 医生</div>
            <div id="navlink">
                <ul>
                    <li><a href="/doctor">个人主页</a></li>
                    <li><a href="/create_account1">创建账号</a></li>
                    <li><a href="/create_article">推文上传</a></li>
                </ul>
            </div>
            <div id="toip">
                锦华中医诊所
            </div>
            <div id="left">
                <form id="article" action="/update_patient_information/{{patient_id}}" method="POST">
                    <div id="article_title" class="kind">
                        &emsp;<span>患者姓名 ：<input type="text" id="topic1" name="name" value="{{name}}" placeholder="请输入主题" ></span>&emsp;&emsp;&emsp;&emsp;&emsp;
                        <span>疾病类别 : <input type="text" id="category" name="category" value="{{category}}" placeholder="请输入类型" ></span>
                        <br>
                        <span style="float:left">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 医生姓名 ：{{ user_name }}&emsp;&emsp;&emsp;&emsp;</span>
                        <span style="float:left">日期 : {{ time }}</span>
                    </div>

                    <div id="article_content"><textarea name="content" placeholder="请输入有关病人的相关信息" style="width: 99.5%;height: 99%;resize: none;border: blue">{{content}}</textarea></div>
                    <input type="submit" id="topic" value="保存" style="width: 32.5%;margin-left: 30%;margin-right: 30%;margin-top: 4%; background-color:rgb(25, 207, 89);height: 50px;color: white;font-size: 30px;float: left;border: none;">
                    </form>
            </div>
            <div id="right">

                <div id="sousuokuang">
                    <p style="color:rgb(18, 211, 20);background-color:rgb(226, 239, 225);width:100%;font-family:Noto Sans SC;font-size:45px;margin-top:0px;margin-bottom:3px;border-radius:15px;padding-top:15px;padding-bottom:15px;float:left">病人名称&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</p>
                    <br><form action="{{url_for('doctor.search_for_update')}}" method="post">
                    <input id="search" type="text" value="{{contents}}" name="search">
                    <input id="anniu" type="submit" value="搜索">
                    </form>
                </div>
            </div>
            <div id="contactinformation" style="color:white">
                <span style="color:rgb(18, 211, 20)">Traditional Chinese medicine</span>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<span style="color:rgb(148, 155, 149)"> 联系邮箱：plli2021@lzu.edu.cn 联系电话；13831122775</span>
            </div>
        </div>
    </body>
</html>

src/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>登录页面</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body{
                /* web 1920 */
                position: relative;
                background: rgb(255, 255, 255);
                width: 100%;
            }
            .container {
                position: relative;
                width: 100%;
                height: 20%;
                top: 160px;
                left: 0;
            }
            .litt{
                /* XX医馆个性化养生方案推送系统 */
                float: left;
                width: 87%;
                height: 61px;
                top: 0;
                left: 0;
                color: rgb(105, 229, 13);
                font-size: 36px;
                font-weight: 400;
                line-height: 53px;
                letter-spacing: 0px;
                text-align: left;
            }
            .litt1{
                /* 您好， 请先登录 */
                float: left;
                width: 13%;
                height: 61px;
                top: 0;
                left: 81.7%;
                color: rgb(0, 0, 0);
                font-size: 36px;
                font-weight: 400;
                line-height: 53px;
                letter-spacing: 0px;
                text-align: left;
            }

            .container2{
                position: absolute;
                width: 100%;
                height: 61px;
                top: 747px;
                left: 0;
                background: rgba(196, 196, 196, 0.13);
            }

            .container6{
                position: absolute;
                width: 100%;
                height: 110px;
                top: 625px;
                left: 0;
                background: rgb(30, 229, 57);
            } 

            input{
                position: absolute;
                width: 23.4%;
                height: 60px;
                top: 820px;
                left: 39%;
                box-sizing: border-box;
                background: rgba(196, 196, 196, 0.41);
                border: 1px solid rgb(0, 0, 0);
                box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
            }
            a{
                color: rgb(36, 226, 38);
                font-family: Noto Sans SC;
                font-size: 36px;
                font-weight: 400;
                line-height: 53px;
                letter-spacing: 0px;
                text-align: left;
            }
        </style>
    </head>
    <body class="body">
        <script type="text/javascript">
            window.onload = function () {
                document.getElementById("regbtn").onclick = function () {
                    if (用户名和密码正确) {
                        //提交
                        var formObj = document.getElementById("userform");
                        //通过调用submit()来完成表单的提交
                        formObj.submit();
                    }

                }
            }

        </script>
        <div class="litt">
            <h6 style="color: #1EE539">锦华中医馆个性化养生方案推送系统</h6>
        </div>
        <div class="litt1">
            <h6>您好，请先登录</h6>
        </div>
        <div class="container">
            <img src="{{ url_for('static', filename='main.png') }}" style="width: 100%;
                height: auto;">
        </div>
        <div class = "container6"></div>
        <div>
            <form action="{{url_for('index.login')}}" method="POST">
                <input type="text"  name="username" id="username" placeholder="{{value1}}" />
                <br>
                <input type="text" name="password" id="password" placeholder="{{value2}}" style="top: 899px; left: 39%;"/><span id="passwordwrong"></span>
                <br>
                <input type="submit" value="登录" id="regbtn" style="position: absolute;width: 23.4%;height: 60px;top: 980px;left: 39%;background: rgb(20, 197, 22);">
            </form>
        </div>



    </body>
</html>

src/templates/patient.html
<!DOCTYPE html>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/Other/html.html to edit this template
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <style>
           #top1{
               border-style: solid;
               border-color: #330033;
               border-radius: 30px;
               background-color:#33ff00;
               height: 100px;
               width: 230px;
               float:right;
               }
               
            #else1{
                border-style: solid;
               border-color: black;
               border-radius: 30px;
               background-color: yellow;
               height: 600px;
               width: 625px;
               float:left;
            }
            #else2{
               border-style: solid;
               border-color: black;
               border-radius: 30px;
               background-color: #ff3333;
               height: 600px;
               width: 900px;
               float:right;
            }
            #else3{
                 border-style: solid;
               border-color: pink;
               border-radius: 30px;
               background-color: #66ff66;
               height: 600px;
               width: 600px;
               float:right;
        }
        #else4{
               border-style: solid;
               border-color: #33ffff;
               border-radius: 30px;
               background-color: #66ff66;
               height: 200px;
               width: 300px;
               float:left;
        }
        #footer1{
            line-hight: 60px;
             border-style: solid;
             border-color: #33ffff;
             border-radius: 30px;
             background-color: #f0f0f0;
             height: 300px;
             width: 800px;
             float:right;
        }

       </style>
    </head>
    <body>
        <link rel ="stylesheet" type = "text/css" href="newcss for TCM.css">
   
       <h2 style="color: #66ff66; font-size: 60px; text-align: left">XX医馆个性化养生方案推送系统</h2>
      <div id="top1"> <h2 style="color: #330033; font-size: 40px; float: right"> 您好， XXX  </h2></div>
      <h2 style="color: #66ff66; font-size: 60px; float: center"> 您的主页</h2>
      <img src="hp.jpg" alt="alt"/ style="width: 2100px;hight: 1500px; float:center">
      <div id="else1">
       <a href="https://www.baidu.com">   <p style="color:greenyellow; font-size: 50px;">针对胃的养生方式</p></a>
       <a href="https://www.baidu.com">    <p style="color: black; font-size:50px;">针对脾的养生方式</p></a>
       <a href="https://www.baidu.com">   <p style="color: black; font-size:50px;">针对阴虚的养生方式</p></a>
       <a href="https://www.baidu.com">     <p style="color: black; font-size:50px;">您的诊断信息</p></a>
          </div>
          
       <div id="else3">
             <p style="color: black; font-size:50px; text-align: right;">日期</p>
             <br>
             <br>
               <p style="color: black; font-size:50px; text-align: right;">日期</p>
           
           </div>
               <br>
     <div id="else2">
      <a href="https://www.baidu.com">   <p style="color: black; font-size:50px;">文章名</p></a>
      <a href="https://www.baidu.com">   <p style="color: black; font-size:50px;">文章名</p></a>
      <a href="https://www.baidu.com">   <p style="color: black; font-size:50px;">文章名</p></a>
         </div>
      <br>
      <div id="else4">
         <a href="https://www.baidu.com"><p style="color:black; font-size: 40px">针对系统提出宝贵意见</p></a>
          <br>
                <a href="https://www.baidu.com"><p style="color:black; font-size: 40px">反馈自身问题</p></a>
          </div>
       <div id="footer1">
           <a href="https://www.baidu.com"><p style="color: black; font-size: 40px">下一页 </p></a>
           </div>
         <div id="footer1">
          <a href="https://www.baidu.com"><p style="color: black; font-size: 40px">上一页 </p></a>
           
           </div>
   
   
          
    
</body>
</html>

src/templates/patientmain.html
<!DOCTYPE html>
<!--
列表内容为李佩伦所写
李政通工作成果：网页主体框架制作，利用css对网页进行美化
-->    
<html>
    <head>
        <title>用户主页</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css"
              href="{{ url_for('static', filename='updown.css') }}">
        <style>
            body{
                background: rgb(255, 255, 255);
            }
            .container1 {
                position: relative;
                width: 100%;
                height: 20%;
                top:50px;
                left: 0;
            }
            .container2{
                position: absolute;
                width:100%;
                height: 300px;
                top: 747px;
                left: 0;
                background: rgba(196, 196, 196, 0.13);
            }

        </style>
    </head>
    <body>
        <div id="container">
            <div id="title"> 您好,{{user_name}}
            </div>
            <div id="navlink">
                <ul>
                    <li style="background-color:rgb(18, 211, 20);"><a href="index.html">个人主页</a></li>
                    <li><a href="{{ url_for('feedback.add_feedback') }}">发送反馈</a></li>
                </ul>
            </div>
                        <div id="toip">
                锦华中医诊所
            </div>

            <div class="container1">
                <img src="{{ url_for('static', filename='main.png') }}" style="width: 100%;
                     height: 500px;">
            </div>
            <div class="container2">
                <ol style="font-size:25px;font-family: Noto Sans SC;width:100%">
                    {% for article in articles %}
                    {% if article[4] in ill %}
                     <div style="width:30%;float:left;font-size:25px;font-family: Noto Sans SC;"> 针对{{ article[4] }}的养生方式 </div>
                     <div style="width:65%;float:left;"> <a href="#" style="font-size:25px;font-family: Noto Sans SC;color: black;">{{ article[1] }}&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{{article[5]}}</a> </div>
                    {% endif %}
                    {% endfor %}
                </ol>
            </div>
        </div>
    </body>
</html>